import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Sandbox from '../components/Sandbox'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          WordPress Sandbox
        </h1>
      
        <Sandbox/>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://prappo.dev"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made with ❤️ by Prappo
        </a>
      </footer>
    </div>
  )
}
